In [2]:
import torch

In [3]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = torch.tensor([9, 8, 7])

In [4]:
torch.matmul(a, b)

tensor([ 46, 118, 190])

In [11]:
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
b

tensor([9, 8, 7])

In [13]:
9*1 + 8*4 + 7*7

90

In [14]:
9*2 + 8*5 + 7*8

114

In [10]:
b @ a

tensor([ 90, 114, 138])

In [6]:
9+16+21

46

In [7]:
9*4 + 8*5 + 7*6

118

In [8]:
9*7 + 8*8 + 7*9

190

In [9]:
a @ b

tensor([ 46, 118, 190])